package crawler;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ProgressIndicator;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.control.ProgressBar;

import javafx.scene.control.ScrollPane;

import javafx.scene.control.Tab;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.ChoiceBox;

import javafx.scene.control.TreeView;

import javafx.scene.input.ContextMenuEvent;

public class Controller {
	@FXML
	private Tab tabCrawl;
	@FXML
	private Label labelURL;
	@FXML
	private Label labelLien;
	@FXML
	private TextField textFielURL;
	@FXML
	private CheckBox checkBoxLien;
	@FXML
	private CheckBox checkBoxIV;
	@FXML
	private Label labelProfondeur;
	@FXML
	private TextField textFieldProfondeur;
	@FXML
	private Button buttonDownload;
	@FXML
	private Label labelLangue1;
	@FXML
	private ChoiceBox choiceBoxLangue1;
	@FXML
	private Label labelRepertoire;
	@FXML
	private TextField textFieldRepertoire;
	@FXML
	private Button buttonParcourir;
	@FXML
	private Label labelDownload1;
	@FXML
	private ProgressBar progressBarDownload1;
	@FXML
	private ProgressIndicator progressIndicatorDownload;
	@FXML
	private Tab tabVisualisation;
	@FXML
	private Label labelLangue2;
	@FXML
	private ChoiceBox choiceBoxLangue2;
	@FXML
	private Label labelDownload2;
	@FXML
	private ProgressBar progressBarDownload2;
	@FXML
	private ProgressIndicator progressIndicator2;
	@FXML
	private TreeView treeView;
	@FXML
	private Button buttonOuvrir;
	@FXML
	private Button buttonSupprimer;
	@FXML
	private ScrollPane scrollPane;

	// Event Listener on CheckBox[#checkBoxLien].onMouseClicked
	@FXML
	public void listenerCheckBox(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#buttonDownload].onMouseClicked
	@FXML
	public void listenerDownload(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#choiceBoxLangue1].onContextMenuRequested
	@FXML
	public void listenerLangueContext1(ContextMenuEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#choiceBoxLangue1].onMouseClicked
	@FXML
	public void listenerLangueClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#buttonParcourir].onMouseClicked
	@FXML
	public void listenerParcourir(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#choiceBoxLangue2].onContextMenuRequested
	@FXML
	public void listenerLangueContext2(ContextMenuEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#choiceBoxLangue2].onMouseClicked
	@FXML
	public void listenerLangueClicked2(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#buttonOuvrir].onMouseClicked
	@FXML
	public void listenerOuvrir(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#buttonSupprimer].onMouseClicked
	@FXML
	public void listenerSupprimer(MouseEvent event) {
		// TODO Autogenerated
	}
}
